# Generated by Django 4.0.4 on 2022-04-28 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_add_slug_to_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='desctiption',
            new_name='description',
        ),
    ]
